"""Updated db

Revision ID: 40e98fbe0776
Revises: fdfab49254c5
Create Date: 2024-02-27 15:15:06.422773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e98fbe0776'
down_revision = 'fdfab49254c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=True))
        batch_op.drop_constraint('FK__Bookings__ticket__18EBB532', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Pricing', ['total'], ['id'])
        batch_op.drop_column('ticket')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__Bookings__ticket__18EBB532', 'Pricing', ['ticket'], ['id'])
        batch_op.drop_column('total')

    # ### end Alembic commands ###
