"""Updated db

Revision ID: ba2495c9ee2b
Revises: 
Create Date: 2024-03-11 11:47:07.089681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2495c9ee2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_soldout', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_ended', sa.Boolean(), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
        batch_op.drop_column('is_ended')
        batch_op.drop_column('is_soldout')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
